services:
  node1-mariadb:
    image: mariadb:12.2
    hostname: node1-mariadb
    container_name: node1-mariadb
    privileged: true
    environment:
      MARIADB_ROOT_PASSWORD: 'iamgroot'
      MARIADB_DATABASE: 'MODEL'
    ports:
      - 13306:3306
    volumes:
      - ./volumes/galeranode1/mariadb:/var/lib/mysql
      - ./sqldir:/docker-entrypoint-initdb.d
    # Usamos command para activar el plugin, pero las variables para el setup inicial
    command:
      - "mariadbd"
      - "--wsrep-on=ON"
      - "--wsrep-provider=/usr/lib/galera/libgalera_smm.so"
      - "--wsrep-cluster-address=gcomm://" # El primero arranca el cluster
      - "--wsrep-cluster-name=maria_cluster"
      - "--wsrep-node-name=node1-mariadb"
      - "--binlog-format=ROW"
      - "--innodb-autoinc-lock-mode=2"

  node2-mariadb:
    image: mariadb:12.2
    hostname: node2-mariadb
    container_name: node2-mariadb
    privileged: true
    depends_on:
      - node1-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 'iamgroot'
    ports:
      - 23306:3306
    volumes:
      - ./volumes/galeranode2/mariadb:/var/lib/mysql
    command:
      - "mariadbd"
      - "--wsrep-on=ON"
      - "--wsrep-provider=/usr/lib/galera/libgalera_smm.so"
      - "--wsrep-cluster-address=gcomm://node1-mariadb"
      - "--wsrep-cluster-name=maria_cluster"
      - "--wsrep-node-name=node2-mariadb"
      - "--binlog-format=ROW"
      - "--innodb-autoinc-lock-mode=2"

  node3-mariadb:
    image: mariadb:12.2
    hostname: node3-mariadb
    container_name: node3-mariadb
    privileged: true
    depends_on:
      - node1-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 'iamgroot'
    ports:
      - 33306:3306
    volumes:
      - ./volumes/galeranode3/mariadb:/var/lib/mysql
    command:
      - "mariadbd"
      - "--wsrep-on=ON"
      - "--wsrep-provider=/usr/lib/galera/libgalera_smm.so"
      - "--wsrep-cluster-address=gcomm://node1-mariadb"
      - "--wsrep-cluster-name=maria_cluster"
      - "--wsrep-node-name=node3-mariadb"
      - "--binlog-format=ROW"
      - "--innodb-autoinc-lock-mode=2"

  haproxy:
    image: haproxytech/haproxy-ubuntu:latest
    container_name: haproxy_mysql
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 2999:2999
      - 3306:3306
    depends_on:
      - node1-mariadb
      - node2-mariadb
      - node3-mariadb