-- Permisos para root (Local y Remoto)
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'iamgroot' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'iamgroot' WITH GRANT OPTION;

-- Usuario de test
CREATE USER IF NOT EXISTS 'testuser'@'%' IDENTIFIED BY 'iamgroot';
GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%';


CREATE SCHEMA IF NOT EXISTS `MODEL` DEFAULT CHARACTER SET utf8 ;
USE `MODEL` ;

FLUSH PRIVILEGES;

