services:
  pxc-certs-gen:
    image: percona/percona-xtradb-cluster:8.4
    hostname: pxc-certs-gen
    container_name: pxc-certs-gen
    user: root
    volumes:
      - ./cert:/cert
      - ./scripts/create-certs.sh:/create-certs.sh:ro
    command: ["/bin/bash", "/create-certs.sh"]

  pxc-node1:
    image: percona/percona-xtradb-cluster:8.4
    hostname: pxc-node1
    container_name: pxc-node1
    environment:
      - MYSQL_ROOT_PASSWORD=test1234#
      - CLUSTER_NAME=pxc-cluster1
    ports:
      - "3307:3306"
    volumes:
      - ./cert:/cert
      - ./config:/etc/percona-xtradb-cluster.conf.d
#    depends_on:
#      pxc-certs-gen:
#        condition: service_completed_successfully
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  pxc-node2:
    image: percona/percona-xtradb-cluster:8.4
    container_name: pxc-node2
    hostname: pxc-node2
    environment:
      - MYSQL_ROOT_PASSWORD=test1234#
      - CLUSTER_NAME=pxc-cluster1
      - CLUSTER_JOIN=pxc-node1
    volumes:
      - ./cert:/cert
      - ./config:/etc/percona-xtradb-cluster.conf.d
#    depends_on:
#      pxc-node1:
#        condition: service_healthy
#      pxc-certs-gen:
#        condition: service_completed_successfully
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  pxc-node3:
    image: percona/percona-xtradb-cluster:8.4
    container_name: pxc-node3
    hostname: pxc-node3
    environment:
      - MYSQL_ROOT_PASSWORD=test1234#
      - CLUSTER_NAME=pxc-cluster1
      - CLUSTER_JOIN=pxc-node1
    volumes:
      - ./cert:/cert
      - ./config:/etc/percona-xtradb-cluster.conf.d
#    depends_on:
#      pxc-node1:
#        condition: service_healthy
#      pxc-certs-gen:
#        condition: service_completed_successfully
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  pxc-lb:
    image: haproxy:latest
    container_name: pxc-lb
    ports:
      - "3306:3306"    # Puerto de entrada para tu app
      - "2999:2999"    # Panel de estadísticas (opcional)
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - pxc-node1
      - pxc-node2
      - pxc-node3